use_frameworks!

platform :ios, '10.0'

target 'GGFoundation_Example' do
  pod 'GGFoundation', :path => '../'

  target 'GGFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
